

import React from 'react';
import type { Product, Category, Brand } from './types';

export const CATEGORIES: Category[] = [
  { id: 'electronics', name: 'Electronics', imageUrl: 'https://picsum.photos/seed/electronics/400/300' },
  { id: 'fashion', name: 'Fashion', imageUrl: 'https://picsum.photos/seed/fashion/400/300' },
  { id: 'home-goods', name: 'Home Goods', imageUrl: 'https://picsum.photos/seed/home-goods/400/300' },
  { id: 'books', name: 'Books', imageUrl: 'https://picsum.photos/seed/books/400/300' },
  { id: 'sports', name: 'Sports', imageUrl: 'https://picsum.photos/seed/sports/400/300' },
  { id: 'toys', name: 'Toys & Games', imageUrl: 'https://picsum.photos/seed/toys/400/300' },
  { id: 'bazaar', name: 'Bazaar', imageUrl: 'https://picsum.photos/seed/bazaar/400/300' },
  { id: 'fresh', name: 'Fresh', imageUrl: 'https://picsum.photos/seed/fresh/400/300' },
  { id: 'health-personal-care', name: 'Health & Personal Care', imageUrl: 'https://picsum.photos/seed/health/400/300' },
  { id: 'beauty', name: 'Beauty', imageUrl: 'https://picsum.photos/seed/beauty/400/300' },
  { id: 'perfumes', name: 'Perfumes', imageUrl: 'https://picsum.photos/seed/perfumes/400/300' },
  { id: 'video-games', name: 'Video Games', imageUrl: 'https://picsum.photos/seed/gaming/400/300' },
  { id: 'grocery-food', name: 'Grocery & Food', imageUrl: 'https://picsum.photos/seed/grocery/400/300' },
  { id: 'automotive', name: 'Automotive', imageUrl: 'https://picsum.photos/seed/automotive/400/300' },
  { id: 'computers', name: 'Computers', imageUrl: 'https://picsum.photos/seed/computers/400/300' },
  { id: 'baby', name: 'Baby', imageUrl: 'https://picsum.photos/seed/baby/400/300' },
];

export const BRANDS: Brand[] = [
  { id: 'apple', name: 'Apple' },
  { id: 'samsung', name: 'Samsung' },
  { id: 'sony', name: 'Sony' },
  { id: 'nike', name: 'Nike' },
  { id: 'adidas', name: 'Adidas' },
  { id: 'random-house', name: 'Random House' },
  { id: 'lego', name: 'LEGO' },
  { id: 'ikea', name: 'IKEA' },
];

export const PRODUCTS: Product[] = [
  {
    id: 1,
    name: 'Smartphone Pro X',
    price: 999.99,
    description: 'Latest flagship smartphone with AI camera.',
    longDescription: 'The Smartphone Pro X features a stunning 6.7-inch Super Retina XDR display, the powerful A17 Bionic chip for incredible performance, and a pro-level camera system for breathtaking photos and videos. With 5G capability and all-day battery life, it\'s the ultimate smartphone experience.',
    category: 'electronics',
    brand: 'samsung',
    imageUrls: ['https://picsum.photos/seed/smartphoneprox/600/600'],
    videoUrl: '',
    rating: 4.8,
    reviewCount: 2345,
    stockQuantity: 25,
    reviews: [
        { id: 101, userName: 'Alex', rating: 5, comment: 'Best phone I have ever owned! The camera is phenomenal.' },
        { id: 102, userName: 'Maria', rating: 4, comment: 'Great performance and battery life, but a bit pricey.' }
    ],
  },
  {
    id: 2,
    name: 'Wireless Noise-Cancelling Headphones',
    price: 349.00,
    description: 'Immersive sound, industry-leading noise cancellation.',
    longDescription: 'Escape the world with these premium wireless headphones. They offer exceptional sound quality, adaptive noise cancellation that adjusts to your environment, and up to 30 hours of battery life on a single charge. Comfortable for all-day wear.',
    category: 'electronics',
    brand: 'sony',
    imageUrls: ['https://picsum.photos/seed/headphones/600/600'],
    videoUrl: '',
    rating: 4.9,
    reviewCount: 5890,
    stockQuantity: 8,
    reviews: [
        { id: 201, userName: 'David', rating: 5, comment: 'The noise cancellation is just magical. Worth every penny.' }
    ],
  },
  {
    id: 3,
    name: 'Ultra-Slim Laptop',
    price: 1299.00,
    description: 'Powerful and portable for work and play.',
    longDescription: 'This ultra-slim laptop combines sleek design with powerful performance. It features a 13.3-inch QHD display, the latest Intel Core i7 processor, 16GB of RAM, and a 512GB SSD. Perfect for professionals and creatives on the go.',
    category: 'computers',
    brand: 'apple',
    imageUrls: ['https://picsum.photos/seed/laptop/600/600'],
    videoUrl: '',
    rating: 4.7,
    reviewCount: 982,
    stockQuantity: 0,
    reviews: [
        { id: 301, userName: 'Jessica', rating: 5, comment: 'So fast and lightweight. Perfect for my work.' },
        { id: 302, userName: 'Tom', rating: 4, comment: 'Excellent laptop, but I wish it had more ports.' }
    ],
  },
  {
    id: 4,
    name: 'Men\'s Running Shoes',
    price: 120.00,
    description: 'Lightweight and responsive for your daily run.',
    longDescription: 'Engineered for comfort and performance, these running shoes feature a breathable mesh upper, responsive foam cushioning, and a durable rubber outsole for excellent traction. Whether you\'re a casual jogger or a marathon runner, these shoes will help you go the distance.',
    category: 'fashion',
    brand: 'nike',
    imageUrls: ['https://picsum.photos/seed/runningshoes/600/600'],
    videoUrl: '',
    rating: 4.6,
    reviewCount: 3122,
    stockQuantity: 150,
    reviews: [
        { id: 401, userName: 'Runner23', rating: 5, comment: 'Super comfortable and provide great support.' }
    ],
  },
  {
    id: 5,
    name: 'Classic Leather Jacket',
    price: 499.50,
    description: 'Timeless style, premium quality leather.',
    longDescription: 'A wardrobe essential, this classic leather jacket is crafted from 100% genuine lambskin leather. It features a sleek, minimalist design with a zip front, side pockets, and a comfortable satin lining. A timeless piece that gets better with age.',
    category: 'fashion',
    brand: 'adidas',
    imageUrls: ['https://picsum.photos/seed/leatherjacket/600/600'],
    videoUrl: '',
    rating: 4.9,
    reviewCount: 754,
    stockQuantity: 5,
    reviews: [
        { id: 501, userName: 'StyleIcon', rating: 5, comment: 'Absolutely stunning jacket. The leather is so soft.' }
    ],
  },
  {
    id: 6,
    name: 'Modern Minimalist Watch',
    price: 250.00,
    description: 'Elegant design with a stainless steel case.',
    longDescription: 'This watch combines minimalist aesthetics with precision engineering. It features a 40mm stainless steel case, a clean white dial with simple markers, and a genuine leather strap. Water-resistant up to 50 meters, it\'s a versatile accessory for any occasion.',
    category: 'fashion',
    brand: 'sony',
    imageUrls: ['https://picsum.photos/seed/watch/600/600'],
    videoUrl: '',
    rating: 4.5,
    reviewCount: 431,
    stockQuantity: 30,
    reviews: [],
  },
  {
    id: 7,
    name: 'Robotic Vacuum Cleaner',
    price: 399.00,
    description: 'Smart navigation and powerful suction.',
    longDescription: 'Keep your floors spotless with this intelligent robotic vacuum. It uses advanced laser navigation to map your home and create an efficient cleaning path. With powerful suction and Wi-Fi connectivity, you can control it from anywhere using the companion app.',
    category: 'home-goods',
    brand: 'samsung',
    imageUrls: ['https://picsum.photos/seed/vacuum/600/600'],
    videoUrl: '',
    rating: 4.7,
    reviewCount: 1560,
    stockQuantity: 0,
    reviews: [
        { id: 701, userName: 'CleanFreak', rating: 5, comment: 'This has changed my life! My floors have never been cleaner.' }
    ],
  },
  {
    id: 8,
    name: 'Espresso Machine',
    price: 650.00,
    description: 'Barista-quality espresso at home.',
    longDescription: 'Craft delicious espresso, lattes, and cappuccinos with this semi-automatic espresso machine. It features a built-in grinder, precise temperature control, and a powerful steam wand for perfect milk frothing. Elevate your morning coffee routine.',
    category: 'home-goods',
    brand: 'ikea',
    imageUrls: ['https://picsum.photos/seed/espresso/600/600'],
    videoUrl: '',
    rating: 4.8,
    reviewCount: 899,
    stockQuantity: 12,
    reviews: [],
  },
  {
    id: 9,
    name: '"The Midnight Library" by Matt Haig',
    price: 15.99,
    description: 'A captivating novel about choices and regrets.',
    longDescription: 'Between life and death there is a library, and within that library, the shelves go on for ever. Every book provides a chance to try another life you could have lived. To see how things would be if you had made other choices . . . Would you have done anything different, if you had the chance to undo your regrets?',
    category: 'books',
    brand: 'random-house',
    imageUrls: ['https://picsum.photos/seed/book1/600/600'],
    videoUrl: '',
    rating: 4.9,
    reviewCount: 12050,
    stockQuantity: 200,
    reviews: [
      { id: 901, userName: 'Bookworm', rating: 5, comment: 'One of the best books I have read this year. So thought-provoking.'}
    ],
  },
  {
    id: 10,
    name: 'Yoga Mat',
    price: 40.00,
    description: 'Non-slip, eco-friendly material.',
    longDescription: 'This premium yoga mat provides excellent grip and cushioning for your practice. Made from eco-friendly, non-toxic materials, it\'s lightweight yet durable. The non-slip surface ensures stability in any pose. Includes a carrying strap for easy transport.',
    category: 'sports',
    brand: 'nike',
    imageUrls: ['https://picsum.photos/seed/yogamat/600/600'],
    videoUrl: '',
    rating: 4.6,
    reviewCount: 987,
    stockQuantity: 9,
    reviews: [],
  },
  {
    id: 11,
    name: 'Space Explorer LEGO Set',
    price: 99.99,
    description: 'Build your own spaceship and explore the galaxy.',
    longDescription: 'Embark on an intergalactic adventure with the Space Explorer LEGO set. This 1,200-piece set includes everything you need to build a detailed spaceship with a cockpit, cargo bay, and detachable rover. Includes 3 astronaut minifigures.',
    category: 'toys',
    brand: 'lego',
    imageUrls: ['https://picsum.photos/seed/lego/600/600'],
    videoUrl: '',
    rating: 4.9,
    reviewCount: 453,
    stockQuantity: 45,
    reviews: [],
  },
  {
    id: 12,
    name: '4K Smart TV 55-inch',
    price: 599.00,
    description: 'Vibrant colors and smart features.',
    longDescription: 'Experience entertainment in stunning 4K Ultra HD. This 55-inch Smart TV delivers incredible picture quality with vibrant colors and sharp details. Access all your favorite streaming apps like Netflix, YouTube, and more directly from the TV.',
    category: 'electronics',
    brand: 'samsung',
    imageUrls: ['https://picsum.photos/seed/tv/600/600'],
    videoUrl: '',
    rating: 4.7,
    reviewCount: 3120,
    stockQuantity: 15,
    reviews: [],
  },
  {
    id: 13,
    name: 'Professional DSLR Camera',
    price: 1999.00,
    description: 'Capture stunning photos and 4K video.',
    longDescription: 'Take your photography to the next level with this professional DSLR camera. It features a 24.2MP full-frame sensor, fast autofocus, and 4K video recording capabilities. The articulating touchscreen makes it easy to shoot from any angle.',
    category: 'electronics',
    brand: 'sony',
    imageUrls: ['https://picsum.photos/seed/camera/600/600'],
    videoUrl: '',
    rating: 4.9,
    reviewCount: 1200,
    stockQuantity: 3,
    reviews: [],
  },
  {
    id: 14,
    name: 'Women\'s Winter Parka',
    price: 250.00,
    description: 'Warm, waterproof, and stylish for cold weather.',
    longDescription: 'Stay warm and dry in the harshest conditions with this stylish winter parka. It features a waterproof and breathable outer shell, premium synthetic insulation, and a faux-fur-trimmed hood. Multiple pockets provide ample storage for your essentials.',
    category: 'fashion',
    brand: 'adidas',
    imageUrls: ['https://picsum.photos/seed/parka/600/600'],
    videoUrl: '',
    rating: 4.8,
    reviewCount: 1543,
    stockQuantity: 60,
    reviews: [],
  },
  {
    id: 15,
    name: 'Designer Sunglasses',
    price: 180.00,
    description: 'Classic aviator style with 100% UV protection.',
    longDescription: 'Protect your eyes in style with these classic aviator sunglasses. They feature a lightweight metal frame, polarized lenses for reduced glare, and 100% UVA/UVB protection. A timeless accessory for any sunny day.',
    category: 'fashion',
    brand: 'nike',
    imageUrls: ['https://picsum.photos/seed/sunglasses/600/600'],
    videoUrl: '',
    rating: 4.7,
    reviewCount: 654,
    stockQuantity: 0,
    reviews: [],
  },
  {
    id: 16,
    name: 'Air Fryer XL',
    price: 119.99,
    description: 'Enjoy your favorite fried foods with less oil.',
    longDescription: 'The Air Fryer XL lets you fry, bake, grill, and roast with little to no oil. Its large 5.8-quart capacity is perfect for families. The digital touchscreen has 8 presets for easy cooking, and the non-stick basket is dishwasher safe.',
    category: 'home-goods',
    brand: 'ikea',
    imageUrls: ['https://picsum.photos/seed/airfryer/600/600'],
    videoUrl: '',
    rating: 4.8,
    reviewCount: 4210,
    stockQuantity: 10,
    reviews: [],
  },
  {
    id: 17,
    name: 'Linen Sheet Set (Queen)',
    price: 189.00,
    description: 'Soft, breathable, and luxurious bedding.',
    longDescription: 'Experience the ultimate in comfort with this 100% pure linen sheet set. Known for its breathability and softness, linen keeps you cool in the summer and warm in the winter. The set includes a flat sheet, a fitted sheet, and two pillowcases.',
    category: 'home-goods',
    brand: 'ikea',
    imageUrls: ['https://picsum.photos/seed/sheets/600/600'],
    videoUrl: '',
    rating: 4.9,
    reviewCount: 321,
    stockQuantity: 22,
    reviews: [],
  },
  {
    id: 18,
    name: '"Sapiens: A Brief History of Humankind"',
    price: 18.50,
    description: 'A thought-provoking look at human history.',
    longDescription: 'In "Sapiens," Dr. Yuval Noah Harari spans the whole of human history, from the very first humans to walk the earth to the radical—and sometimes devastating—breakthroughs of the Cognitive, Agricultural, and Scientific Revolutions.',
    category: 'books',
    brand: 'random-house',
    imageUrls: ['https://picsum.photos/seed/book2/600/600'],
    videoUrl: '',
    rating: 4.9,
    reviewCount: 25000,
    stockQuantity: 300,
    reviews: [],
  },
  {
    id: 19,
    name: 'Adjustable Dumbbells Set',
    price: 349.99,
    description: 'Replaces 15 sets of weights in one.',
    longDescription: 'Save space with this adjustable dumbbell set. With a simple turn of a dial, you can change your resistance from 5 lbs to 52.5 lbs. The perfect solution for a versatile home workout without the clutter of multiple dumbbells.',
    category: 'sports',
    brand: 'nike',
    imageUrls: ['https://picsum.photos/seed/dumbbells/600/600'],
    videoUrl: '',
    rating: 4.7,
    reviewCount: 1876,
    stockQuantity: 0,
    reviews: [],
  },
  {
    id: 20,
    name: '3D Wooden Puzzle Globe',
    price: 59.99,
    description: 'A challenging and beautiful mechanical model.',
    longDescription: 'Build your own ornate globe with this 3D wooden puzzle kit. No glue or tools are required. The finished model is a functional globe that rotates, with intricate details and a secret lockbox. A rewarding project for teens and adults.',
    category: 'toys',
    brand: 'lego',
    imageUrls: ['https://picsum.photos/seed/puzzle/600/600'],
    videoUrl: '',
    rating: 4.8,
    reviewCount: 543,
    stockQuantity: 7,
    reviews: [],
  },
  {
    id: 21,
    name: 'Organic Avocadoes (4-pack)',
    price: 5.99,
    description: 'Fresh and creamy organic Hass avocadoes.',
    longDescription: 'A 4-pack of our finest, hand-picked organic Hass avocadoes. Perfect for toast, salads, guacamole, or a healthy snack. Rich in nutrients and flavor.',
    category: 'fresh',
    brand: 'ikea',
    imageUrls: ['https://picsum.photos/seed/avocadoes/600/600'],
    videoUrl: '',
    rating: 4.9,
    reviewCount: 1200,
    stockQuantity: 150,
    reviews: [],
  },
  {
    id: 22,
    name: 'Artisan Sourdough Bread',
    price: 7.50,
    description: 'Hand-crafted, naturally leavened sourdough.',
    longDescription: 'Our artisan sourdough is made with a traditional starter, organic flour, and a slow fermentation process, resulting in a complex flavor and a perfect crust. Baked fresh daily.',
    category: 'grocery-food',
    brand: 'ikea',
    imageUrls: ['https://picsum.photos/seed/bread/600/600'],
    videoUrl: '',
    rating: 4.8,
    reviewCount: 543,
    stockQuantity: 40,
    reviews: [],
  },
  {
    id: 23,
    name: 'Electric Toothbrush',
    price: 89.99,
    description: 'Removes 100% more plaque than a manual brush.',
    longDescription: 'Achieve a superior clean with this electric toothbrush. Features 3 brushing modes, a 2-minute timer, and a pressure sensor to protect your gums. The battery lasts up to two weeks on a single charge.',
    category: 'health-personal-care',
    brand: 'samsung',
    imageUrls: ['https://picsum.photos/seed/toothbrush/600/600'],
    videoUrl: '',
    rating: 4.7,
    reviewCount: 2109,
    stockQuantity: 60,
    reviews: [],
  },
  {
    id: 24,
    name: 'Vitamin C Serum',
    price: 24.95,
    description: 'Brightening and anti-aging face serum.',
    longDescription: 'This potent Vitamin C serum helps to brighten the complexion, reduce the appearance of fine lines and wrinkles, and protect against environmental stressors. Formulated with hyaluronic acid for added hydration.',
    category: 'beauty',
    brand: 'ikea',
    imageUrls: ['https://picsum.photos/seed/serum/600/600'],
    videoUrl: '',
    rating: 4.6,
    reviewCount: 899,
    stockQuantity: 100,
    reviews: [],
  },
  {
    id: 25,
    name: 'Eau de Parfum - Noir',
    price: 125.00,
    description: 'A mysterious and alluring unisex fragrance.',
    longDescription: 'Noir is a captivating fragrance with notes of blackcurrant, patchouli, and vanilla. A sophisticated and long-lasting scent that is perfect for evening wear. Comes in a stylish 100ml bottle.',
    category: 'perfumes',
    brand: 'sony',
    imageUrls: ['https://picsum.photos/seed/perfume/600/600'],
    videoUrl: '',
    rating: 4.9,
    reviewCount: 1532,
    stockQuantity: 35,
    reviews: [],
  },
  {
    id: 26,
    name: 'Cybernetic Revolt (Video Game)',
    price: 59.99,
    description: 'Action-packed RPG set in a dystopian future.',
    longDescription: 'Immerse yourself in the world of Cybernetic Revolt. As a rogue android, you must fight for freedom in a city controlled by mega-corporations. Features a vast open world, deep character customization, and a branching storyline.',
    category: 'video-games',
    brand: 'sony',
    imageUrls: ['https://picsum.photos/seed/videogame/600/600'],
    videoUrl: '',
    rating: 4.8,
    reviewCount: 6543,
    stockQuantity: 200,
    reviews: [],
  },
  {
    id: 27,
    name: 'Premium Car Wax Kit',
    price: 35.50,
    description: 'Achieve a professional, high-gloss shine.',
    longDescription: 'This complete car wax kit includes everything you need for a showroom finish. The synthetic polymer wax provides long-lasting protection and a deep, wet-look shine. Includes applicator pads and a microfiber towel.',
    category: 'automotive',
    brand: 'ikea',
    imageUrls: ['https://picsum.photos/seed/carwax/600/600'],
    videoUrl: '',
    rating: 4.7,
    reviewCount: 788,
    stockQuantity: 80,
    reviews: [],
  },
  {
    id: 28,
    name: 'Gaming Mechanical Keyboard',
    price: 139.00,
    description: 'RGB backlit keyboard with tactile switches.',
    longDescription: 'Gain a competitive edge with this mechanical gaming keyboard. It features customizable RGB backlighting, responsive tactile switches for speed and accuracy, and a durable aluminum frame. Includes programmable macro keys.',
    category: 'computers',
    brand: 'samsung',
    imageUrls: ['https://picsum.photos/seed/keyboard/600/600'],
    videoUrl: '',
    rating: 4.8,
    reviewCount: 1987,
    stockQuantity: 25,
    reviews: [],
  },
  {
    id: 29,
    name: 'Organic Baby Food Pouches (12-Pack)',
    price: 18.99,
    description: 'A variety pack of organic fruit & veggie purees.',
    longDescription: 'Give your little one the best with our organic baby food pouches. This variety pack includes 12 pouches of delicious fruit and vegetable blends. No added sugar, non-GMO, and BPA-free packaging.',
    category: 'baby',
    brand: 'ikea',
    imageUrls: ['https://picsum.photos/seed/babyfood/600/600'],
    videoUrl: '',
    rating: 4.9,
    reviewCount: 3450,
    stockQuantity: 120,
    reviews: [],
  },
  {
    id: 30,
    name: 'Handwoven Moroccan Rug',
    price: 320.00,
    description: 'Authentic wool rug adds warmth and style.',
    longDescription: 'This beautiful rug was handwoven by artisans in Morocco. Made from 100% natural wool, it features a classic diamond pattern and a plush, comfortable pile. A unique piece of art for your floor.',
    category: 'bazaar',
    brand: 'ikea',
    imageUrls: ['https://picsum.photos/seed/rug/600/600'],
    videoUrl: '',
    rating: 4.9,
    reviewCount: 150,
    stockQuantity: 10,
    reviews: [],
  },
  {
    id: 31, name: 'Smart Water Bottle', price: 69.99, description: 'Tracks water intake and glows to remind you to drink.',
    longDescription: 'Stay hydrated with the smart water bottle that tracks your sips and syncs with an app. The bottle glows to remind you to drink throughout the day, helping you reach your hydration goals.',
    category: 'health-personal-care', brand: 'samsung', imageUrls: ['https://picsum.photos/seed/waterbottle/600/600'], videoUrl: '',
    rating: 4.6, reviewCount: 450, stockQuantity: 55, reviews: [],
  },
  {
    id: 32, name: 'Air Purifier', price: 149.50, description: 'Removes 99.97% of airborne particles.',
    longDescription: 'Breathe cleaner air with this HEPA air purifier. It captures dust, pollen, pet dander, and smoke particles. Features a quiet mode for nighttime use and an auto mode that adjusts fan speed based on air quality.',
    category: 'home-goods', brand: 'samsung', imageUrls: ['https://picsum.photos/seed/airpurifier/600/600'], videoUrl: '',
    rating: 4.8, reviewCount: 2310, stockQuantity: 30, reviews: [],
  },
  {
    id: 33, name: 'Pro Gaming Mouse', price: 79.00, description: 'Ultra-lightweight mouse with a high-precision sensor.',
    longDescription: 'Designed for esports professionals, this gaming mouse weighs only 60 grams for fast movements. It has a 16,000 DPI optical sensor for pixel-perfect tracking and customizable buttons.',
    category: 'computers', brand: 'sony', imageUrls: ['https://picsum.photos/seed/mouse/600/600'], videoUrl: '',
    rating: 4.9, reviewCount: 1800, stockQuantity: 70, reviews: [],
  },
  {
    id: 34, name: 'Portable Bluetooth Speaker', price: 99.00, description: '360-degree sound, waterproof and dustproof.',
    longDescription: 'Take your music anywhere with this rugged portable speaker. It offers powerful 360-degree sound, is IP67 waterproof and dustproof, and has a battery life of up to 15 hours.',
    category: 'electronics', brand: 'sony', imageUrls: ['https://picsum.photos/seed/speaker/600/600'], videoUrl: '',
    rating: 4.7, reviewCount: 4500, stockQuantity: 100, reviews: [],
  },
  {
    id: 35, name: 'Ergonomic Baby Carrier', price: 129.99, description: 'Comfortable for both baby and parent.',
    longDescription: 'This baby carrier offers multiple carrying positions to grow with your child from newborn to toddler. It features padded shoulder straps and lumbar support for parent comfort, and an ergonomic seat for the baby.',
    category: 'baby', brand: 'nike', imageUrls: ['https://picsum.photos/seed/carrier/600/600'], videoUrl: '',
    rating: 4.8, reviewCount: 980, stockQuantity: 40, reviews: [],
  },
  {
    id: 36, name: 'Digital Tire Inflator', price: 45.99, description: 'Portable air compressor for your car.',
    longDescription: 'Never get caught with a flat tire again. This portable digital tire inflator plugs into your car\'s 12V outlet. Set your desired pressure on the LCD screen, and it will automatically shut off when reached.',
    category: 'automotive', brand: 'samsung', imageUrls: ['https://picsum.photos/seed/inflator/600/600'], videoUrl: '',
    rating: 4.6, reviewCount: 1240, stockQuantity: 90, reviews: [],
  },
  {
    id: 37, name: 'Hydrating Face Mask Set', price: 19.99, description: 'Set of 5 sheet masks for glowing skin.',
    longDescription: 'Pamper your skin with this set of 5 hydrating sheet masks. Each mask is infused with a different natural ingredient like aloe, honey, or green tea to soothe, moisturize, and revitalize your complexion.',
    category: 'beauty', brand: 'ikea', imageUrls: ['https://picsum.photos/seed/facemask/600/600'], videoUrl: '',
    rating: 4.7, reviewCount: 650, stockQuantity: 200, reviews: [],
  },
  {
    id: 38, name: '"The Alchemist" by Paulo Coelho', price: 12.99, description: 'An inspiring modern classic.',
    longDescription: 'Paulo Coelho\'s enchanting novel has inspired a devoted following around the world. This story, dazzling in its powerful simplicity and soul-stirring wisdom, is about an Andalusian shepherd boy named Santiago who travels from his homeland in Spain to the Egyptian desert in search of a treasure buried near the Pyramids.',
    category: 'books', brand: 'random-house', imageUrls: ['https://picsum.photos/seed/book3/600/600'], videoUrl: '',
    rating: 4.8, reviewCount: 35000, stockQuantity: 400, reviews: [],
  },
  {
    id: 39, name: 'Gourmet Olive Oil', price: 22.50, description: 'Extra virgin olive oil from single-origin olives.',
    longDescription: 'Elevate your cooking with this premium extra virgin olive oil. Cold-pressed from hand-picked Kalamata olives, it has a rich, fruity flavor with a peppery finish. Perfect for dressings, dipping, and finishing dishes.',
    category: 'grocery-food', brand: 'ikea', imageUrls: ['https://picsum.photos/seed/oliveoil/600/600'], videoUrl: '',
    rating: 4.9, reviewCount: 430, stockQuantity: 80, reviews: [],
  },
  {
    id: 40, name: 'Insulated Tumbler', price: 29.95, description: 'Keeps drinks hot for 12 hours or cold for 24 hours.',
    longDescription: 'This 30 oz stainless steel tumbler features double-wall vacuum insulation to keep your beverages at the perfect temperature. It comes with a splash-proof lid and fits in most car cup holders.',
    category: 'bazaar', brand: 'nike', imageUrls: ['https://picsum.photos/seed/tumbler/600/600'], videoUrl: '',
    rating: 4.8, reviewCount: 3210, stockQuantity: 150, reviews: [],
  },
  {
    id: 41, name: 'Classic Board Game Collection', price: 49.99, description: 'A collection of 10 classic board games.',
    longDescription: 'This collection is perfect for family game night. It includes 10 timeless classics like Chess, Checkers, Backgammon, and more, all housed in a beautiful wooden storage box.',
    category: 'toys', brand: 'lego', imageUrls: ['https://picsum.photos/seed/boardgames/600/600'], videoUrl: '',
    rating: 4.7, reviewCount: 765, stockQuantity: 60, reviews: [],
  },
  {
    id: 42, name: 'Floral Bloom Eau de Toilette', price: 75.00, description: 'A light and fresh floral fragrance for women.',
    longDescription: 'Experience the scent of a garden in full bloom. This fragrance features notes of jasmine, tuberose, and rangoon creeper. A delicate and feminine scent perfect for daytime wear.',
    category: 'perfumes', brand: 'adidas', imageUrls: ['https://picsum.photos/seed/perfume2/600/600'], videoUrl: '',
    rating: 4.7, reviewCount: 890, stockQuantity: 50, reviews: [],
  },
  {
    id: 43, name: 'Resistance Bands Set', price: 25.99, description: 'Set of 5 loop bands for a full-body workout.',
    longDescription: 'This set includes 5 resistance bands of varying levels, from extra light to extra heavy. Perfect for strength training, physical therapy, and home workouts. Comes with a convenient travel bag.',
    category: 'sports', brand: 'adidas', imageUrls: ['https://picsum.photos/seed/bands/600/600'], videoUrl: '',
    rating: 4.6, reviewCount: 1500, stockQuantity: 200, reviews: [],
  },
  {
    id: 44, name: 'Galaxy Quest (Video Game)', price: 49.99, description: 'Explore a vast, procedurally generated universe.',
    longDescription: 'Captain your own starship in Galaxy Quest. Explore uncharted planets, trade with alien species, and engage in epic space battles. With a universe of billions of planets, the adventure is endless.',
    category: 'video-games', brand: 'lego', imageUrls: ['https://picsum.photos/seed/spacegame/600/600'], videoUrl: '',
    rating: 4.5, reviewCount: 3210, stockQuantity: 150, reviews: [],
  },
  {
    id: 45, name: 'Memory Foam Pillow', price: 59.99, description: 'Ergonomic pillow for neck support and pain relief.',
    longDescription: 'Wake up refreshed with this ergonomic memory foam pillow. It is designed to support the natural curve of your neck, promoting proper spinal alignment and relieving pressure points. Comes with a breathable, washable cover.',
    category: 'health-personal-care', brand: 'ikea', imageUrls: ['https://picsum.photos/seed/pillow/600/600'], videoUrl: '',
    rating: 4.7, reviewCount: 1890, stockQuantity: 80, reviews: [],
  },
  {
    id: 46, name: 'Cashmere Scarf', price: 110.00, description: 'Incredibly soft and luxurious 100% cashmere.',
    longDescription: 'Wrap yourself in luxury with this ultra-soft cashmere scarf. It is lightweight yet incredibly warm, making it the perfect accessory for chilly weather. Available in several classic colors.',
    category: 'fashion', brand: 'adidas', imageUrls: ['https://picsum.photos/seed/scarf/600/600'], videoUrl: '',
    rating: 4.9, reviewCount: 320, stockQuantity: 40, reviews: [],
  },
  {
    id: 47, name: '27-inch 4K Monitor', price: 349.00, description: 'Stunning visuals for work and entertainment.',
    longDescription: 'Upgrade your desktop setup with this 27-inch 4K monitor. It delivers breathtaking clarity and vibrant colors with HDR support. The ultra-thin bezel design is perfect for multi-monitor setups.',
    category: 'computers', brand: 'samsung', imageUrls: ['https://picsum.photos/seed/monitor/600/600'], videoUrl: '',
    rating: 4.8, reviewCount: 1400, stockQuantity: 30, reviews: [],
  },
  {
    id: 48, name: 'Dash Cam', price: 89.99, description: 'Records in 1080p and has a wide-angle lens.',
    longDescription: 'Protect yourself on the road with this compact dash cam. It records in crisp 1080p, and the 170-degree wide-angle lens captures the entire road ahead. Features loop recording and a G-sensor for automatic incident detection.',
    category: 'automotive', brand: 'sony', imageUrls: ['https://picsum.photos/seed/dashcam/600/600'], videoUrl: '',
    rating: 4.6, reviewCount: 2150, stockQuantity: 100, reviews: [],
  },
  {
    id: 49, name: 'Diaper Bag Backpack', price: 49.99, description: 'Stylish and functional with lots of storage.',
    longDescription: 'This diaper bag doesn\'t sacrifice style for function. It has multiple compartments, insulated bottle pockets, and a built-in changing pad. The backpack design keeps your hands free.',
    category: 'baby', brand: 'nike', imageUrls: ['https://picsum.photos/seed/diaperbag/600/600'], videoUrl: '',
    rating: 4.8, reviewCount: 1700, stockQuantity: 70, reviews: [],
  },
  {
    id: 50, name: 'Silk Pillowcase', price: 35.00, description: 'Reduces hair frizz and is gentle on skin.',
    longDescription: 'Wake up with smoother hair and skin. This 100% mulberry silk pillowcase reduces friction, preventing hair breakage and sleep creases on your face. It\'s naturally hypoallergenic and temperature-regulating.',
    category: 'beauty', brand: 'ikea', imageUrls: ['https://picsum.photos/seed/silkpillow/600/600'], videoUrl: '',
    rating: 4.9, reviewCount: 1100, stockQuantity: 90, reviews: [],
  },
  {
    id: 51, name: 'Cast Iron Skillet', price: 39.95, description: 'Pre-seasoned and ready to use for a lifetime of cooking.',
    longDescription: 'A must-have in any kitchen, this 12-inch cast iron skillet offers superior heat retention and even cooking. It comes pre-seasoned and is perfect for searing, frying, baking, and more.',
    category: 'home-goods', brand: 'ikea', imageUrls: ['https://picsum.photos/seed/skillet/600/600'], videoUrl: '',
    rating: 4.9, reviewCount: 5400, stockQuantity: 60, reviews: [],
  },
  {
    id: 52, name: 'Organic Matcha Green Tea Powder', price: 24.99, description: 'Ceremonial grade matcha for lattes and tea.',
    longDescription: 'Our ceremonial grade matcha is sourced from the finest tea leaves in Japan. It has a vibrant green color and a smooth, rich flavor. Perfect for making traditional matcha tea or delicious lattes.',
    category: 'fresh', brand: 'ikea', imageUrls: ['https://picsum.photos/seed/matcha/600/600'], videoUrl: '',
    rating: 4.8, reviewCount: 850, stockQuantity: 100, reviews: [],
  },
  {
    id: 53, name: 'Smartwatch Fitness Tracker', price: 159.00, description: 'Tracks heart rate, sleep, and activities.',
    longDescription: 'This smartwatch helps you stay on top of your fitness goals. It tracks your heart rate, steps, calories burned, and sleep quality. Receive notifications from your phone and choose from dozens of watch faces.',
    category: 'electronics', brand: 'samsung', imageUrls: ['https://picsum.photos/seed/smartwatch/600/600'], videoUrl: '',
    rating: 4.7, reviewCount: 3200, stockQuantity: 80, reviews: [],
  },
  {
    id: 54, name: 'Leather Wallet', price: 49.50, description: 'Slim bifold wallet with RFID blocking.',
    longDescription: 'Crafted from genuine leather, this slim wallet is designed for the modern minimalist. It features multiple card slots, a bill compartment, and RFID-blocking technology to protect your information.',
    category: 'fashion', brand: 'adidas', imageUrls: ['https://picsum.photos/seed/wallet/600/600'], videoUrl: '',
    rating: 4.8, reviewCount: 950, stockQuantity: 120, reviews: [],
  },
  {
    id: 55, name: 'Pickleball Paddle Set', price: 69.99, description: 'Includes 2 paddles, 4 balls, and a carrying case.',
    longDescription: 'Get started with the fastest-growing sport in the country. This pickleball set includes two lightweight graphite paddles with comfortable grips, four balls, and a convenient bag to carry it all to the court.',
    category: 'sports', brand: 'nike', imageUrls: ['https://picsum.photos/seed/pickleball/600/600'], videoUrl: '',
    rating: 4.7, reviewCount: 600, stockQuantity: 90, reviews: [],
  },
  {
    id: 56, name: 'Webcam 1080p', price: 49.99, description: 'Full HD webcam with built-in microphone for streaming.',
    longDescription: 'Look your best on video calls and streams with this 1080p webcam. It features a sharp, smooth video feed and a built-in noise-canceling microphone for clear audio. Plug and play via USB.',
    category: 'computers', brand: 'sony', imageUrls: ['https://picsum.photos/seed/webcam/600/600'], videoUrl: '',
    rating: 4.6, reviewCount: 2500, stockQuantity: 110, reviews: [],
  },
  {
    id: 57, name: 'Turkish Cotton Bath Towels (Set of 4)', price: 79.00, description: 'Plush, absorbent, and durable luxury towels.',
    longDescription: 'Wrap yourself in five-star hotel luxury. These towels are made from 100% long-staple Turkish cotton, making them exceptionally soft, absorbent, and durable. This set includes four generously sized bath towels.',
    category: 'bazaar', brand: 'ikea', imageUrls: ['https://picsum.photos/seed/towels/600/600'], videoUrl: '',
    rating: 4.9, reviewCount: 1300, stockQuantity: 50, reviews: [],
  }
];

// SVG Icons as React Components for easy use
export const ICONS = {
  // FIX: Corrected SVG property from strokeLineCap to strokeLinecap and strokeLineJoin to strokeLinejoin.
  cart: <svg xmlns="http://www.w3.org/2000/svg" className="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M3 3h2l.4 2M7 13h10l4-8H5.4M7 13L5.4 5M7 13l-2.293 2.293c-.63.63-.184 1.707.707 1.707H17m0 0a2 2 0 100 4 2 2 0 000-4zm-8 2a2 2 0 11-4 0 2 2 0 014 0z" /></svg>,
  // FIX: Corrected SVG property from strokeLineCap to strokeLinecap and strokeLineJoin to strokeLinejoin.
  search: <svg xmlns="http://www.w3.org/2000/svg" className="h-5 w-5" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z" /></svg>,
  starFull: <svg xmlns="http://www.w3.org/2000/svg" className="h-5 w-5 text-yellow-400" viewBox="0 0 20 20" fill="currentColor"><path d="M9.049 2.927c.3-.921 1.603-.921 1.902 0l1.07 3.292a1 1 0 00.95.69h3.462c.969 0 1.371 1.24.588 1.81l-2.8 2.034a1 1 0 00-.364 1.118l1.07 3.292c.3.921-.755 1.688-1.54 1.118l-2.8-2.034a1 1 0 00-1.175 0l-2.8 2.034c-.784.57-1.838-.197-1.539-1.118l1.07-3.292a1 1 0 00-.364-1.118L2.98 8.72c-.783-.57-.38-1.81.588-1.81h3.461a1 1 0 00.951-.69l1.07-3.292z" /></svg>,
  starHalf: <svg xmlns="http://www.w3.org/2000/svg" className="h-5 w-5 text-yellow-400" viewBox="0 0 20 20" fill="currentColor"><path d="M9.049 2.927c.3-.921 1.603-.921 1.902 0l1.07 3.292a1 1 0 00.95.69h3.462c.969 0 1.371 1.24.588 1.81l-2.8 2.034a1 1 0 00-.364 1.118l1.07 3.292c.3.921-.755 1.688-1.54 1.118l-2.8-2.034a1 1 0 00-1.175 0l-2.8 2.034c-.784.57-1.838-.197-1.539-1.118l1.07-3.292a1 1 0 00-.364-1.118L2.98 8.72c-.783-.57-.38-1.81.588-1.81h3.461a1 1 0 00.951-.69l1.07-3.292z" /></svg>,
  starEmpty: <svg xmlns="http://www.w3.org/2000/svg" className="h-5 w-5 text-gray-300" viewBox="0 0 20 20" fill="currentColor"><path d="M9.049 2.927c.3-.921 1.603-.921 1.902 0l1.07 3.292a1 1 0 00.95.69h3.462c.969 0 1.371 1.24.588 1.81l-2.8 2.034a1 1 0 00-.364 1.118l1.07 3.292c.3.921-.755 1.688-1.54 1.118l-2.8-2.034a1 1 0 00-1.175 0l-2.8 2.034c-.784.57-1.838-.197-1.539-1.118l1.07-3.292a1 1 0 00-.364-1.118L2.98 8.72c-.783-.57-.38-1.81.588-1.81h3.461a1 1 0 00.951-.69l1.07-3.292z" /></svg>,
  // FIX: Corrected SVG property from strokeLineCap to strokeLinecap and strokeLineJoin to strokeLinejoin.
  heartOutline: <svg xmlns="http://www.w3.org/2000/svg" className="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M4.318 6.318a4.5 4.5 0 016.364 0L12 7.5l1.318-1.182a4.5 4.5 0 116.364 6.364L12 21l-7.682-7.682a4.5 4.5 0 010-6.364z" /></svg>,
  heartFull: <svg xmlns="http://www.w3.org/2000/svg" className="h-6 w-6 text-red-500" viewBox="0 0 20 20" fill="currentColor"><path fillRule="evenodd" d="M3.172 5.172a4 4 0 015.656 0L10 6.343l1.172-1.171a4 4 0 115.656 5.656L10 17.657l-6.828-6.829a4 4 0 010-5.656z" clipRule="evenodd" /></svg>,
  // FIX: Corrected SVG property from strokeLineCap to strokeLinecap and strokeLineJoin to strokeLinejoin.
  location: <svg xmlns="http://www.w3.org/2000/svg" className="h-5 w-5" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M17.657 16.657L13.414 20.9a1.998 1.998 0 01-2.827 0l-4.244-4.243a8 8 0 1111.314 0z" /><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M15 11a3 3 0 11-6 0 3 3 0 016 0z" /></svg>,
};

export const CATEGORY_ICONS: { [key: string]: React.ReactElement } = {
  // FIX: Corrected SVG property from strokeLineCap to strokeLinecap and strokeLineJoin to strokeLinejoin.
  electronics: <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" strokeWidth={1.5} stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" d="M10.5 1.5H8.25A2.25 2.25 0 006 3.75v16.5a2.25 2.25 0 002.25 2.25h7.5A2.25 2.25 0 0018 20.25V3.75a2.25 2.25 0 00-2.25-2.25H13.5m-3 0V3h3V1.5m-3 0h3m-3 18.75h3" /></svg>,
  // FIX: Corrected SVG property from strokeLineCap to strokeLinecap and strokeLineJoin to strokeLinejoin.
  fashion: <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" strokeWidth={1.5} stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" d="M9 12h6m-6 4h6m2 5H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" /></svg>,
  // FIX: Corrected SVG property from strokeLineCap to strokeLinecap and strokeLineJoin to strokeLinejoin.
  'home-goods': <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" strokeWidth={1.5} stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" d="M12 18v-5.25m0 0a6.01 6.01 0 001.5-.189m-1.5.189a6.01 6.01 0 01-1.5-.189m3.75 7.478a12.06 12.06 0 01-4.5 0m3.75 2.311a15.045 15.045 0 01-7.5 0C4.508 19.64 3 17.418 3 15V8.812a1.5 1.5 0 01.88-1.356l6-3.75a1.5 1.5 0 011.24 0l6 3.75A1.5 1.5 0 0121 8.812V15c0 2.418-1.508 4.64-3.75 5.062z" /></svg>,
  // FIX: Corrected SVG property from strokeLineCap to strokeLinecap and strokeLineJoin to strokeLinejoin.
  books: <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" strokeWidth={1.5} stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" d="M12 6.042A8.967 8.967 0 006 3.75c-1.052 0-2.062.18-3 .512v14.25A8.987 8.987 0 016 18c2.305 0 4.408.867 6 2.292m0-14.25a8.966 8.966 0 016-2.292c1.052 0 2.062.18 3 .512v14.25A8.987 8.987 0 0018 18a8.967 8.967 0 00-6 2.292m0-14.25v14.25" /></svg>,
  // FIX: Corrected SVG property from strokeLineCap to strokeLinecap and strokeLineJoin to strokeLinejoin.
  sports: <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" strokeWidth={1.5} stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" d="M10.5 6h9.75M10.5 6a1.5 1.5 0 11-3 0m3 0a1.5 1.5 0 10-3 0M3.75 6H7.5m3 12h9.75m-9.75 0a1.5 1.5 0 01-3 0m3 0a1.5 1.5 0 00-3 0m-3.75 0H7.5m9-6h3.75m-3.75 0a1.5 1.5 0 01-3 0m3 0a1.5 1.5 0 00-3 0m-9.75 0h9.75" /></svg>,
  // FIX: Corrected SVG property from strokeLineCap to strokeLinecap and strokeLineJoin to strokeLinejoin.
  toys: <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" strokeWidth={1.5} stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" d="M21 7.5l-2.25-1.313M21 7.5v2.25m0-2.25l-2.25 1.313M3 7.5l2.25-1.313M3 7.5l2.25 1.313M3 7.5v2.25m9 3l2.25-1.313M12 12.75l-2.25 1.313M12 12.75V15m0 6.75l2.25-1.313M12 21.75V19.5m0 2.25l-2.25-1.313m0-16.875L12 2.25l2.25 1.313M21 14.25v2.25l-2.25 1.313m-13.5 0L3 16.5v-2.25" /></svg>,
  // FIX: Corrected SVG property from strokeLineCap to strokeLinecap and strokeLineJoin to strokeLinejoin.
  bazaar: <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" strokeWidth={1.5} stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" d="M13.5 21v-7.5A.75.75 0 0114.25 12h.01a.75.75 0 01.75.75v7.5m-3.75 0v-7.5a.75.75 0 00-.75-.75h-.01a.75.75 0 00-.75.75v7.5m-3.75 0v-7.5A.75.75 0 016.75 12h.01a.75.75 0 01.75.75v7.5m6-15V6m-3-3v3m-3-3v3M3.375 6.51c.421-.244.877-.442 1.35-.615m14.55 0c.473.173.93.37 1.35.615m-17.25 11.565c1.15-.67 2.512-1.1 3.96-1.32M20.625 18.075c-1.448.22-2.81.65-3.96 1.32M3.75 9.75h16.5" /></svg>,
  // FIX: Corrected SVG property from strokeLineCap to strokeLinecap and strokeLineJoin to strokeLinejoin.
  fresh: <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" strokeWidth={1.5} stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" d="M12 3v2.25m6.364.386l-1.591 1.591M21 12h-2.25m-.386 6.364l-1.591-1.591M12 18.75V21m-4.773-4.227l-1.591 1.591M5.25 12H3m4.227-4.773L5.636 5.636M15.75 12a3.75 3.75 0 11-7.5 0 3.75 3.75 0 017.5 0z" /></svg>,
};